#!/usr/bin/env python3
#
# Copyright 2021 Maksym Medvied
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
TODO add common test parameters: get timeout, get list of steps.
"""


from plumbum import FG
from plumbum.cmd import docker


targets_and_tags = [
    ('check', 'mze-check:test'),
    ('build', 'mze-build:test'),
    ('exec', 'mze:test'),
]


def main() -> None:
    for target, tag in targets_and_tags:
        cmd = docker['build', '--file', 'Dockerfile.python',
                     '--target', target, '--tag', tag, '.']
        print(' '.join(cmd.formulate()), flush=True)
        cmd & FG


if __name__ == '__main__':
    main()
