#!/usr/bin/env python3
#
# Copyright 2021 Maksym Medvied
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from plumbum import local, FG

from common import common


flake8 = local['python']['-m', 'flake8',  # '--verbose',
                         '--show-source', '--statistics']

TARGETS = [
    *common.python_file_list('test/*'),
    *common.python_file_list('test/common/*'),
    'src/',
]


def main() -> None:
    for target in TARGETS:
        flake8[target] & FG


if __name__ == '__main__':
    main()
