#!/usr/bin/env python3
#
# Copyright 2021 Maksym Medvied
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import os
import glob

from plumbum import local, FG


mypy = local['python'][
    '-m', 'mypy',
    # '--verbose',
    '--strict',
    '--warn-unreachable',
    '--show-error-context',
    '--show-error-codes',
    '--pretty',
    '--no-incremental',
]

# TODO use relative dir
PYTHONPATH = '/data/src'
TARGETS = [
    ['-p', 'mze'],
    *[[s] for s in sorted(glob.glob('test/common/*'))],
]


def main() -> None:
    global PYTHONPATH
    if 'PYTHONPATH' in os.environ:
        PYTHONPATH = f'{PYTHONPATH}:{os.environ["PYTHONPATH"]}'
    with local.env(PYTHONPATH=PYTHONPATH, MYPYPATH=PYTHONPATH):
        for target in TARGETS:
            mypy[target] & FG


if __name__ == '__main__':
    main()
