#!/usr/bin/env python3
#
# Copyright 2021 Maksym Medvied
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

'''
TODO use local mirror for the packages (dependencies)
TODO remove all versions of package before upload
TODO unhardcode root user
'''


from pathlib import Path

from plumbum import local, FG
from plumbum.cmd import python


def main() -> None:
    version = local['grep']['^version = ', 'setup.cfg']().strip().split()[-1]
    print(f'Current version: {version}', flush=True)
    Path('/root/.config/pip').mkdir(parents=True)
    for f, target in [('pip.conf', '/root/.config/pip/pip.conf'),
                      ('.pypirc', '/root/.pypirc')]:
        print(f'Setting up {target}.', flush=True)
        ((local['envsubst'] < f'cicd/{f}.local.envsubst') > target)()
    packages = [f'dist/{s}' for s in
                [f'mze-{version}.tar.gz',
                 f'mze-{version}-py3-none-any.whl']]
    python['-m', 'twine', 'upload', '--repository', 'local'][packages] & FG


if __name__ == '__main__':
    main()
