[package]
name = "mze"
version = "0.1.0"
edition = "2021"

[dependencies]
color-backtrace = "0.6.1"
env_logger = "0.11.6"
log = "0.4.22"
rand = "0.8.5"
rand_core = "0.6.4"
rand_pcg = "0.3.1"
rusqlite = "0.32.1"
thiserror = "2.0.9"
