# Copyright 2021 Maksym Medvied
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3"

services:
  pr-nginx-1:
    image: nginx:1.21
    depends_on:
      - ss-dir-1
      - ss-dir-2
      - rs-file-on-ss-1
    ports:
      - "80:80"
    volumes:
      - "../../proxy/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "../../storage-server/dir/ss-dir-1.nginx.conf:/etc/nginx/location.d/ss-dir-1.nginx.conf"
      - "../../storage-server/dir/ss-dir-2.nginx.conf:/etc/nginx/location.d/ss-dir-2.nginx.conf"
      - "../../record-server/file-on-ss/rs-file-on-ss-1.nginx.conf:/etc/nginx/location.d/rs-file-on-ss-1.nginx.conf"

  ss-dir-1:
    build:
      dockerfile: "storage-server/dir/Dockerfile"
      context: "${REPO_ROOT}"
    working_dir: "/data/storage-server/dir"
    ports:
      - "11001:80"
    volumes:
      - "../..:/data"
    environment:
      - "MZE_DESCRIPTION=data storage"
      - MZE_WEB_LOCATION=/ss-dir-1
      - MZE_INSTANCE_UUID=88cd23f8-ad7c-4518-8356-ab2b26b5ec04
      - MZE_STORAGE_DIR=/storage

  ss-dir-2:
    build:
      dockerfile: "storage-server/dir/Dockerfile"
      context: "${REPO_ROOT}"
    working_dir: "/data/storage-server/dir"
    ports:
      - "11002:80"
    volumes:
      - "../..:/data"
    environment:
      - "MZE_DESCRIPTION=metadata storage"
      - MZE_WEB_LOCATION=/ss-dir-2
      - MZE_INSTANCE_UUID=0b54f8f6-ff81-4cf6-a388-5fd62ef8bb6c
      - MZE_STORAGE_DIR=/storage

  rs-file-on-ss-1:
    build:
      dockerfile: "record-server/file-on-ss/Dockerfile"
      context: "${REPO_ROOT}"
    depends_on:
      - ss-dir-2
    working_dir: "/data/record-server/file-on-ss"
    ports:
      - "11011:80"
    volumes:
      - "../..:/data"
    environment:
      - "MZE_DESCRIPTION=metadata server"
      - MZE_WEB_LOCATION=/rs-file-on-ss-1
      - MZE_INSTANCE_UUID=68e97e5f-a630-4d7f-9633-69ad4e9734b5
      - MZE_SS_URL=http://ss-dir-2/ss-dir-2/
