version: "3"

services:
  pr-nginx-1:
    image: nginx:1.21
    depends_on:
      - ss-dir-1
    ports:
      - "80:80"
    volumes:
      - "../../proxy/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "../../storage-server/dir/ss-dir.nginx.conf:/etc/nginx/location.d/ss-dir.nginx.conf"

  ss-dir-1:
    build:
      dockerfile: "${REPO_ROOT}/storage-server/dir/Dockerfile"
      context: "./empty"
    working_dir: "/data/storage-server/dir"
    ports:
      - "11000:80"
    volumes:
      - "../..:/data"
    environment:
      - MZE_WEB_LOCATION=/ss-dir-1
      - MZE_INSTANCE_UUID=88cd23f8-ad7c-4518-8356-ab2b26b5ec04
      - MZE_STORAGE_DIR=/storage
